# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: JAMSoftware.UltraSearch
PackageVersion: "4.7"
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: UltraSearch_is1
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.jam-software.de/ultrasearch/archive/v4.7.0.1162/UltraSearch-Setup.exe
  InstallerSha256: 27C795CED96008020E3D04D6714BFFAF5B6F8975EAD4407818FD4E9ECC4F0492
ManifestType: installer
ManifestVersion: 1.9.0
