# Created with YamlCreate.ps1 v2.2.1 $debug=NVS1.CRLF.5-1-22621-963.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: AlickolliSoftware.RandomNumberGenerator(UWP)
PackageVersion: 1.0.0.0
PackageLocale: en-US
Publisher: Alickolli Software
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
Author: Alickolli Software
PackageName: Random Number Generator (UWP)
# PackageUrl:
License: Freeware
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: A random number generator that generates a number between two values
# Description:
# Moniker:
# Tags:
# Agreements:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.2.0
