# Created with YamlCreate.ps1 v2.4.4 $debug=NVS1.CRLF.5-1-26100-2161.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: xHybred.NvidiaProfileInspectorRevamped
PackageVersion: "3.7"
PackageLocale: en-US
Publisher: NvidiaProfileInspectorRevamped
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
PackageName: NvidiaProfileInspectorRevamped
PackageUrl: https://github.com/xHybred/NvidiaProfileInspectorRevamped
License: MIT
LicenseUrl: https://github.com/xHybred/NvidiaProfileInspectorRevamped?tab=License-1-ov-file
# Copyright:
# CopyrightUrl:
ShortDescription: Nvidia Profile Inspector (NPI) is an open source third-party tool created for pulling up and editing application profiles within the Nvidia display drivers.
Description: More settings such as RTX HDR and Dynamic Vibrance, overrides for DLSS 3.1+, image sharpening, Stereocopic viewing options, Improved usability of the search/filter field (automatically applies as you type, can be cleared using the "escape" key), Bug fixes, Improved error messaging, Faster load times
Moniker: nvidiaprofileinspector
# Tags:
# ReleaseNotes:
ReleaseNotesUrl: https://github.com/xHybred/NvidiaProfileInspectorRevamped/releases/tag/v3.7
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.9.0
