# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: TechSmith.Snagit.2024
PackageVersion: 25.1.1
PackageLocale: en-US
Publisher: TechSmith Corporation
PublisherUrl: https://www.techsmith.com/
PublisherSupportUrl: https://support.techsmith.com/
PrivacyUrl: https://www.techsmith.com/privacy-policy.html
Author: TechSmith Corporation
PackageName: Snagit 2024
PackageUrl: https://www.techsmith.com/screen-capture.html
License: Proprietary
LicenseUrl: https://www.techsmith.com/snagit-eula.html
Copyright: Copyright 1996-2024 TechSmith Corp. All rights reserved.
ShortDescription: Screen capture and screen recording software from TechSmith.
Description: Snagit helps you quickly share information in a way that's easy to understand. Capture your screen and camera, add additional context and move work forward faster.
Moniker: snagit-2024
Tags:
- capture
- record
- recording
- screen-capture
- screenshot
- video
PurchaseUrl: https://www.techsmith.com/snagit-pricing.html
Documentations:
- DocumentLabel: Tutorials
  DocumentUrl: https://www.techsmith.com/learn/tutorials/snagit/
ManifestType: defaultLocale
ManifestVersion: 1.9.0
