# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: TechSmith.Snagit.2024
PackageVersion: 25.1.1
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
